# Generated by Django 3.1.8 on 2021-04-25 17:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='MealRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meal_relations', to='restaurants.meal', verbose_name='Meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_relations', to='restaurants.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='meals',
            field=models.ManyToManyField(related_name='orders', through='restaurants.MealRelations', to='restaurants.Meal', verbose_name='Meals'),
        ),
    ]
