# Generated by Django 3.1.8 on 2021-04-25 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0005_auto_20210425_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_restaurants', to=settings.AUTH_USER_MODEL, verbose_name='Blocked Users'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('canceled', 'Canceled'), ('processing', 'Processing'), ('in_route', 'In route'), ('delivered', 'Delivered'), ('received', 'Received')], default='placed', max_length=16, verbose_name='Status'),
        ),
    ]
