# Generated by Django 3.1.8 on 2021-04-25 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20210425_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrelations',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_relations', to='restaurants.meal', verbose_name='Meal'),
        ),
    ]
