# Generated by Django 3.1.8 on 2021-04-24 18:36

from django.db import migrations, models
import helpers.s3
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=helpers.s3.UploadFileTo('accounts', 'image'), verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_restaurant',
            field=models.BooleanField(default=False, verbose_name='Is Restaurant owner'),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
